apiVersion: v1
kind: Namespace
metadata:
  name: kafka
---
apiVersion: v1
kind: Namespace
metadata:
  name: redis
---
apiVersion: v1
kind: Namespace
metadata:
  name: otel-lgtm
---
apiVersion: v1
kind: Namespace
metadata:
  name: mcp-dice-roller
---
apiVersion: v1
kind: Namespace
metadata:
  name: mcp-destinations
---
apiVersion: v1
kind: Namespace
metadata:
  name: mcp-flights
---
apiVersion: v1
kind: Namespace
metadata:
  name: mcp-book-flights
---
apiVersion: v1
kind: Namespace
metadata:
  name: rest-destinations
---
apiVersion: v1
kind: Namespace
metadata:
  name: rest-flights
---
apiVersion: v1
kind: Namespace
metadata:
  name: rest-book-flights
---
apiVersion: v1
kind: Namespace
metadata:
  name: netshoot
---
apiVersion: v1
kind: Namespace
metadata:
  name: keycloak
---
apiVersion: v1
kind: Namespace
metadata:
  name: llm-analytics
---
apiVersion: v1
kind: Namespace
metadata:
  name: metallb-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: traefik
---
apiVersion: v1
kind: Namespace
metadata:
  name: litellm
---
apiVersion: v1
kind: Namespace
metadata:
  name: agentgateway-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: travel-agency-langgraph
