apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-ui
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-ui
  template:
    metadata:
      labels:
        app: kafka-ui
    spec:
      containers:
        - name: kafka-ui
          image: provectuslabs/kafka-ui:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: KAFKA_CLUSTERS_0_NAME
              value: ai-lab
            - name: KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS
              value: kafka.kafka.svc.cluster.local:9092
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-ui
  namespace: kafka
  annotations:
    metallb.universe.tf/loadBalancerIPs: "172.18.255.205"
spec:
  type: LoadBalancer
  selector:
    app: kafka-ui
  ports:
    - port: 8080
      targetPort: 8080
